version: 2.1 # use CircleCI 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/gelato-V1-ci # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:12.16.2 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # Compile
          name: Compile
          command: npx buidler compile
      - run: # Buidlerevm RPC node
          name: Spin up buidlerevm node on localhost RPC
          # || true makes buidler node process return 0 when pkill node
          command: npx buidler node || true
          # important: buidler node as background process
          background: true
      - run: # Tests
          name: Tests and Gas Report on buidlerevm RPC
          command: yarn test
      - run: # Shut down buidler node
          name: Shut down buidlerevm node
          command: pkill node
          when: always
      - run: # Coverage
          name: yarn coverage
          command: yarn coverage
      - coveralls/upload # upload lcov.info to coveralls.io
    #   - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
    #       path: coverage
    #       prefix: coverage
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
